# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#
# This workflow uses actions that are not certified by GitHub. They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
#
# This file contains the workflows that are run prior to merging a pull request.

name: CI

on:
  push:
    branches:
      - 'main'
#      - 'develop'
  pull_request:
    branches:
      - 'main'
#      - 'develop'

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

jobs:
  build_documentation:
    name: Build and package documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Avona
        uses: actions/checkout@v2
      
      - name: Pull doc_builder container
        run: |
          docker pull ghcr.io/xmos/doc_builder:main 
      
      - name: Build documentation
        run: |
          #docker run --rm -t -v ${{ github.workspace }}:/build -u "$(id -u):$(id -g)" -e REPO:/build -e PDF=1 ghcr.io/xmos/doc_builder:main
      
      - name: Save documentation artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sw_avona_docs
          path: ./doc/_build/latest/html
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn` 
          retention-days: 5
